spring:
  application:
    name: capacity-coordinator-service
  config:
    activate:
      on-profile: offline
    import: "optional:configtree:/run/secrets/"
  data:
    mongodb:
      username: microservice
      password: ${mongodb_user_password}
      database: renderDB
  boot:
    admin:
      client:
        enabled: false
    configuration:
      bind:
        ignore-unknown-fields: true
server:
  port: 8082
  shutdown: graceful
# endpoint exposure
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  security:
    enable: false
wfsm:
  pool:
    #  Maximum size of the pool. Default is -1, indicating no size limit.
    maxSize: 50
    # Minimum number of idle objects in the pool.
    minIdle: 8
    # Minimum time that an idle object can sit in the pool before it becomes subject to eviction. Default is 1800000 (30 minutes).
    minEvictableIdleTime: 60000
    # Time between eviction runs that check idle objects whether they have been idle for too long or have become invalid. Default is -1, not performing any eviction.
    timeBetweenEvictionRuns: 60000
    # Maximum waiting time for fetching an object from the pool.
    maxWait: 2000
url:
  frontend: frontend
  broker: broker
  orchestrator: orchestrator

render-output-files:
  bucket-name: render-dev-output-bucket

orchestrator-config:
  timeout-threshold: 30

service-url:
  endpoints:
    - name: frontend
      protocol: http
      host: manager.render-offline
      port: 8081
      path: /api/v1/updates
    - name: broker
      protocol: http
      host: broker.render-offline
      port: 8082
      path: /
    - name: orchestrator
      protocol: http
      host: orchestrator.render-offline
      port: 8083
      path: /scenario
    - name: client
      protocol: grpc
      host: broker.render-offline
      port: 8001
      path: /

afsim-config:
  templates:
    - file: afsimScenarioTemplate
      directory: top
    - file: StartupTemplate
      directory: top
      types: SimpleScenario
      includeBlockBlue: "platform <instanceName> <packageName>
   mover
      inclination <inclination> degrees
      semi_major_axis <LengthUnit> kilometers
      raan <raan> degrees
      true_anomaly <anomaly> degrees
   end_mover
end_platform"
      includeBlockBlue2: "platform <instanceName> <packageName>
  position <lat>n <long>e 
  altitude <altitude> ft
end_platform"
      includeBlockRedScenarios: "include scenarios/<instanceName>.txt"
      includeBlockRedPlatforms: "include_once platforms/<instanceName>.txt"
    - file: MissileTemplate
      directory: platforms
      types: SimpleMissile
    - file: MissileTargetTemplate
      directory: platforms
      types: SimpleTarget
    - file: GEPTemplate
      directory: platforms
      types: SimpleGEP
    - file: SVTemplate
      directory: platforms
      types: SimpleT1TL, SimpleT1TRK
    - file: IRSensorTemplate
      directory: sensors
      types: IR_Sensor
    - file: KaBandTemplate
      directory: comms
      types: Ka_Band_Terminal
    - file: OctTemplate
      directory: comms
      types: OCT
    - file: GEPTemplate
      directory: comms
      types: OC
    - file: MissileParameters
      directory: weapons
    - file: show_spent_stages
      directory: weapons
    - file: typical_ballistic_missile_aero
      directory: weapons
    - file: missile_launch_data
      directory: weapons
    - file: scripts
      directory: scripts
    - file: StartupTemplate
      directory: top
      types: topLevel
      includeBlockBlue: "platform <instanceName> <packageName>
   mover
      inclination <inclination> degrees
      semi_major_axis <LengthUnit> kilometers
      raan <raan> degrees
      true_anomaly <anomaly> degrees
   end_mover
end_platform"
      includeBlockBlue2: "platform <instanceName> <packageName>
  position <lat>n <long>e 
  altitude <altitude> ft
end_platform"
      includeBlockRedScenarios: "include scenarios/<instanceName>.txt"
      includeBlockRedPlatforms: "include_once platforms/<instanceName>.txt"
    - file: MissileTemplate
      directory: platforms
      types: missile
    - file: MissileTargetTemplate
      directory: platforms
      types: target
    - file: GEPTemplate
      directory: platforms
      types: ground
    - file: UserTerminal_Template
      directory: platforms
      types: ground
    - file: SVTemplate
      directory: platforms
      types: space
    - file: IRSensorTemplate
      directory: sensors
      types: irsensor
    - file: KaBandTemplate
      directory: comms
      types: kaband
    - file: OctTemplate
      directory: comms
      types: oct
    - file: GEPTemplate
      directory: comms
      types: oc
