spring:
  application:
    name: capacity-coordinator-service
server:
  port: 8084
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  security:
    enable: false